config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  root 'recipes#index'
end

app/models/recipe.rb
require 'httparty'

class Recipe
  include HTTParty

  key_value = ENV['FOOD2FORK_KEY']
  hostport = ENV['FOOD2FORK_SERVER_AND_PORT'] || 'www.food2fork.com'
  base_uri "http://#{hostport}/api"
  default_params key: key_value
  format :json

  def self.for (keyword)
    get("/search", query: {q: keyword})["recipes"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  	if !params[:search].nil?
  	else
  		params[:search] = "chocolate"
  	end
  	@recipes = Recipe.for(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipefinder - Find yours today!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<h1>RecipeFinder</h1>
	</header>

	<%= yield %>

	<footer class="footer">
		<p>Powered By Food2Fork.com</p>
	</footer>

</body>
</html>

app/views/recipes/index.html.erb
<div class="container">
	<div>
		<h2>Search for a recipe today!</h2>
		<p>Search up your favorite recipe, just put input the ingredients you want in it(commas between ingredients!) and voila!</p>
	</div>
	<div class="search container">
		<%= form_tag recipes_index_path, method: :get, id: 'search' do %>
			<%= label_tag :ingredient %>
			<%= text_field_tag :search , '', placeholder: 'Enter what you\' hungry for' , :required => true %>
			<%= submit_tag "Search", class: 'btn btn-success' %>
		<% end %>
	</div>

	<% unless params[:search].nil? %>
	<div class="results">
		<h2>Results for <%= params[:search] %>(<%= @recipes.count %>)</h2>
		<hr>
		<table border="1" class="col-md-offset-3 col-xs-offset-3">
		  <tr>
		  	<th>Thumbnail</th>
		  	<th>Title</th>
		  	<th>Social Rank</th>
		  </tr>
		  <% @recipes.each do |recipe| %>
		    <tr class=<%= cycle('even', 'odd') %>>
		      <td><%= link_to(image_tag(recipe["image_url"]), recipe['f2f_url'])%></td>
		      <td><%= link_to(sanitize(recipe["title"]), recipe['f2f_url']) %></td>
		      <td><%= sprintf '%.2f', recipe["social_rank"] %></td>
		    </tr>
		  <% end %>
		</table>

	</div>
	<% end %>
</div>